[package]
name = "discrete_count"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "discrete_count_core"
]

[dependencies]
discrete_count_core = { version = "0.1.0", path = "discrete_count_core" }

